# Generated by Django 4.0.3 on 2022-04-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_dog_user_alter_dog_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogToy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
    ]
