# Generated by Django 4.0.3 on 2022-04-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_dogtoy'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='dogtoys',
            field=models.ManyToManyField(to='main_app.dogtoy'),
        ),
    ]
